#!/usr/bin/env bash
# finding out what's keeping your Ubuntu container's Nginx installation from listening on port 80.containerwhat
sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo service nginx restart